### ISSUE TITLE
Error - Preload failed API version mismatch

### ISSUE THREAD

**Issue by TheMany172** [gebeto/flipper-xbox-controller#3]
Used to work fine - now get this error when trying to run

**Comment by TheMany172** [comment]
probably a firmware thing - is there a certain firmware(s) that this would work on?

(have tried the app in all fiolders and the root of the 'apps' folder)

**Comment by gebeto** [comment]
I see that Flipper firmware latest version now is 0.77.1, so I've tried to rebuild app with latest firmware, so now it is not working on my older version, so theoretically it should work for you

https://github.com/gebeto/flipper-xbox-controller/releases/tag/v1.0.1

**Comment by TheMany172** [comment]
Ah that's great, can confirm it is working again
